project:
  type: website
  output-dir: docs

website:
  title: "Steven Le"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - resume.qmd
      - f1-racetracks.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    page-layout: full



